import os
import stat

from cvslab import data


def test_fixture_source_is_deterministic(lab):
    a = data.create_fixture_source(lab.store, n_games=6, seed=7)
    b = data.create_fixture_source(lab.store, n_games=6, seed=7)
    assert a.content_hash == b.content_hash
    assert a.row_count > 0 and a.game_count == 6
    assert a.license.startswith("generated by the lab")


def test_normalize_dedups_identical_sources(lab):
    first = data.create_fixture_source(lab.store, n_games=6, seed=3)
    second = data.create_fixture_source(lab.store, n_games=6, seed=3)  # identical bytes, new identity
    once = data.normalize(lab.store, [first.id], name="once")
    twice = data.normalize(lab.store, [first.id, second.id], name="twice")
    assert twice.record_count == once.record_count
    assert twice.duplicate_count == once.record_count


def test_freeze_dataset_splits_are_game_disjoint(lab):
    source = data.create_fixture_source(lab.store, n_games=40, seed=11)
    norm = data.normalize(lab.store, [source.id], name="n")
    dataset = data.freeze_dataset(lab.store, norm.id, name="d")
    assert sum(s.count for s in dataset.splits) == dataset.counts["records"] == norm.record_count
    checks = {c.name: c for c in data.verify_dataset(lab.store, dataset)}
    assert checks["split_disjoint"].status == "pass"
    assert checks["dataset_files"].status == "pass"


def test_selection_and_label_requirements(lab):
    source = data.create_fixture_source(lab.store, n_games=30, seed=5)
    norm = data.normalize(lab.store, [source.id], name="n")
    endgame = data.freeze_dataset(lab.store, norm.id, name="endgame-only", selection={"phase": "endgame"})
    assert endgame.coverage["phase"] == {"endgame": endgame.counts["records"]}
    every = data.freeze_dataset(lab.store, norm.id, name="all", required_labels=())
    assert every.counts["records"] >= endgame.counts["records"]


def test_tampered_dataset_fails_verification(lab, tmp_path):
    source = data.create_fixture_source(lab.store, n_games=12, seed=9)
    norm = data.normalize(lab.store, [source.id], name="n")
    dataset = data.freeze_dataset(lab.store, norm.id, name="d")
    path = lab.store.abs(dataset.splits[0].path)
    os.chmod(path, stat.S_IWRITE)
    path.write_bytes(path.read_bytes() + b'{"record_id":"pos_forged"}\n')
    checks = {c.name: c for c in data.verify_dataset(lab.store, dataset)}
    assert checks["dataset_files"].status == "fail"


def test_normalize_rejects_tampered_source(lab):
    source = data.create_fixture_source(lab.store, n_games=6, seed=1)
    path = lab.store.abs(source.path)
    os.chmod(path, stat.S_IWRITE)
    path.write_bytes(path.read_bytes() + b'{"fen":"bad"}\n')
    from cvslab.store import TamperError
    try:
        data.normalize(lab.store, [source.id], name="n")
    except TamperError:
        pass
    else:
        raise AssertionError("normalization must refuse a source whose bytes changed after snapshotting")
