"""Data lineage: S#### sources -> N#### normalization -> canonical records -> D#### frozen datasets."""
from __future__ import annotations

import random
import shutil
import time
from collections import Counter
from itertools import combinations
from pathlib import Path
from typing import Mapping, Optional, Sequence

import chess

from .hashing import hash_obj, read_jsonl, sha256_bytes, sha256_file, write_jsonl
from .schemas import (
    Compute,
    ConfigValue,
    Dataset,
    IntegrityCheck,
    Normalization,
    SourceSnapshot,
    SplitManifest,
    make_check,
    utc_now,
)
from .store import LabError, Store, TamperError

FIXTURE_GENERATOR = "cvslab.fixture.random_play"
FIXTURE_GENERATOR_VERSION = 1
IMPORTER = "cvslab.import.jsonl"
IMPORTER_VERSION = 1
MATERIAL_AUTHORITY = "deterministic.material.v1"
NORMALIZER = "cvslab.normalize"
NORMALIZER_VERSION = 1
CANONICAL_SCHEMA_VERSION = 1
DEDUP_POLICIES = ("exact-epd-keep-first", "none")
SELECTABLE_FIELDS = ("phase", "stm", "source_id")
SPLIT_NAMES = ("train", "val", "test")

PIECE_VALUES = {chess.PAWN: 100, chess.KNIGHT: 320, chess.BISHOP: 330, chess.ROOK: 500, chess.QUEEN: 900}


class _Meter:
    def __init__(self):
        self.cpu, self.wall = time.process_time(), time.perf_counter()

    def compute(self, **fields) -> Compute:
        return Compute(cpu_seconds=round(time.process_time() - self.cpu, 4),
                       wall_seconds=round(time.perf_counter() - self.wall, 4), **fields)


def material_cp_white(board: chess.Board) -> int:
    return sum(value * (len(board.pieces(piece, chess.WHITE)) - len(board.pieces(piece, chess.BLACK)))
               for piece, value in PIECE_VALUES.items())


def game_phase(board: chess.Board) -> str:
    non_pawn = sum(value * len(board.pieces(piece, color))
                   for piece, value in PIECE_VALUES.items() if piece != chess.PAWN
                   for color in (chess.WHITE, chess.BLACK))
    return "opening" if non_pawn >= 5600 else "middlegame" if non_pawn >= 2600 else "endgame"


def material_signature(board: chess.Board) -> str:
    def side(color: chess.Color) -> str:
        return "".join(f"{chess.piece_symbol(p).upper()}{len(board.pieces(p, color))}"
                       for p in (chess.QUEEN, chess.ROOK, chess.BISHOP, chess.KNIGHT, chess.PAWN))
    return f"{side(chess.WHITE)}/{side(chess.BLACK).lower()}"


def _ply_from_fen(fen: str) -> int:
    fields = fen.split()
    fullmove = int(fields[5]) if len(fields) > 5 else 1
    return 2 * (fullmove - 1) + (1 if len(fields) > 1 and fields[1] == "b" else 0)


def infer_games(rows: Sequence[dict]) -> list[str]:
    """Game identity: explicit `game` field, else a new game whenever the ply counter does not advance."""
    games, game, previous = [], 0, None
    for row in rows:
        if "game" in row:
            games.append(str(row["game"]))
            continue
        ply = _ply_from_fen(row.get("fen", ""))
        if previous is not None and ply <= previous:
            game += 1
        previous = ply
        games.append(f"g{game:06d}")
    return games


# ---------------------------------------------------------------------------
# L0 sources
# ---------------------------------------------------------------------------


def create_fixture_source(store: Store, *, name: str = "fixture-random-play", n_games: int = 300, seed: int = 20260914,
                          max_plies: int = 80, sample_every: int = 2, min_ply: int = 6) -> SourceSnapshot:
    """Deterministic, license-free tiny corpus: seeded random legal games labelled with material balance."""
    if n_games < 1 or max_plies < 1 or sample_every < 1:
        raise LabError("fixture needs n_games, max_plies and sample_every >= 1")
    meter = _Meter()
    rng = random.Random(seed)
    rows = []
    for game in range(n_games):
        board = chess.Board()
        for ply in range(1, max_plies + 1):
            moves = sorted(board.legal_moves, key=lambda move: move.uci())
            if not moves:
                break
            board.push(rng.choice(moves))
            if board.is_game_over():
                break
            if ply >= min_ply and ply % sample_every == 0:
                rows.append({"game": f"g{game:05d}", "ply": ply, "fen": board.fen(), "cp": material_cp_white(board),
                             "res": None, "label_authority": MATERIAL_AUTHORITY})
    source_id = store.next_id("S")
    rel = f"sources/{source_id}/positions.jsonl"
    content_hash = write_jsonl(store.abs(rel), rows)
    store.make_readonly(store.abs(rel))
    return store.create(SourceSnapshot(
        id=source_id, name=name, source_origin=f"generated by {FIXTURE_GENERATOR} v{FIXTURE_GENERATOR_VERSION}",
        locality="local",
        generator={"name": FIXTURE_GENERATOR, "version": FIXTURE_GENERATOR_VERSION, "seed": seed, "n_games": n_games,
                   "max_plies": max_plies, "sample_every": sample_every, "min_ply": min_ply},
        license="generated by the lab; contains no third-party content",
        importer=FIXTURE_GENERATOR, importer_version=FIXTURE_GENERATOR_VERSION, path=rel, content_hash=content_hash,
        row_count=len(rows), game_count=len({row["game"] for row in rows}), label_authorities=[MATERIAL_AUTHORITY],
        compute=meter.compute(labels_generated={MATERIAL_AUTHORITY: len(rows)}, accepted_examples=len(rows)),
        created_at=utc_now(),
    ))


def import_jsonl_source(store: Store, path: str | Path, *, name: str, license: str = "unspecified",
                        label_authority: str = "imported.unspecified", origin: Optional[str] = None) -> SourceSnapshot:
    """Snapshot a `{fen, cp, res}` JSONL corpus byte-for-byte into the store (L0 is never rewritten)."""
    src = Path(path)
    if not src.is_file():
        raise LabError(f"source file not found: {src}")
    meter = _Meter()
    source_id = store.next_id("S")
    rel = f"sources/{source_id}/{src.name}"
    dest = store.abs(rel)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    store.make_readonly(dest)
    rows = read_jsonl(dest)
    return store.create(SourceSnapshot(
        id=source_id, name=name, source_origin=origin or str(src.resolve()), locality="local", generator=None, license=license,
        importer=IMPORTER, importer_version=IMPORTER_VERSION, path=rel, content_hash=sha256_file(dest),
        row_count=len(rows), game_count=len(set(infer_games(rows))), label_authorities=[label_authority],
        compute=meter.compute(accepted_examples=len(rows)), created_at=utc_now(),
    ))


# ---------------------------------------------------------------------------
# L1 canonical records
# ---------------------------------------------------------------------------


def normalize(store: Store, source_ids: Sequence[str], *, name: str, dedup: str = "exact-epd-keep-first") -> Normalization:
    if dedup not in DEDUP_POLICIES:
        raise LabError(f"unknown dedup policy {dedup!r}; choose one of {DEDUP_POLICIES}")
    if not source_ids:
        raise LabError("normalization needs at least one source")
    meter = _Meter()
    sources: list[SourceSnapshot] = [store.get_as(sid, SourceSnapshot) for sid in source_ids]
    for src in sources:
        if sha256_file(store.abs(src.path)) != src.content_hash:
            raise TamperError(f"{src.id}: source bytes no longer match the snapshot hash")
    settings: dict[str, ConfigValue] = {
        "label_family": "eval_cp",
        "label_pov": "white",
        "phase_rule": "non-pawn material >= 5600 opening, >= 2600 middlegame, else endgame",
        "record_identity": "sha256(EPD) — position without move clocks",
    }
    seen: set[str] = set()
    records, duplicates, rejected = [], 0, 0
    for src in sources:
        rows = read_jsonl(store.abs(src.path))
        for row_index, (row, game) in enumerate(zip(rows, infer_games(rows))):
            try:
                board = chess.Board(row["fen"])
                if not board.is_valid():
                    raise ValueError("illegal position")
            except (KeyError, ValueError):
                rejected += 1
                continue
            epd = board.epd()
            record_id = "pos_" + sha256_bytes(epd.encode())[7:27]
            if dedup == "exact-epd-keep-first":
                if record_id in seen:
                    duplicates += 1
                    continue
                seen.add(record_id)
            labels = []
            if row.get("cp") is not None:
                labels.append({"family": "eval_cp", "value": row["cp"], "pov": "white",
                               "authority": row.get("label_authority") or src.label_authorities[0],
                               "producer": src.id, "label_schema_version": 1})
            records.append({
                "record_id": record_id, "group": f"{src.id}:{game}", "source_id": src.id, "source_row": row_index,
                "ply": row.get("ply", _ply_from_fen(row["fen"])), "fen": board.fen(), "epd": epd,
                "stm": "w" if board.turn == chess.WHITE else "b", "phase": game_phase(board),
                "material": material_signature(board), "labels": labels, "result": row.get("res"),
            })
    normalization_id = store.next_id("N")
    rel = f"canonical/{normalization_id}/records.jsonl"
    output_hash = write_jsonl(store.abs(rel), records)
    store.make_readonly(store.abs(rel))
    source_hashes = {src.id: src.content_hash for src in sources}
    return store.create(Normalization(
        id=normalization_id, name=name, source_ids=list(source_ids), source_hashes=source_hashes, normalizer=NORMALIZER,
        normalizer_version=NORMALIZER_VERSION, canonical_schema_version=CANONICAL_SCHEMA_VERSION, settings=settings,
        dedup_policy=dedup,
        recipe_hash=hash_obj({"source_hashes": source_hashes, "normalizer": NORMALIZER, "version": NORMALIZER_VERSION,
                              "canonical_schema_version": CANONICAL_SCHEMA_VERSION, "settings": settings, "dedup": dedup}),
        path=rel, output_hash=output_hash, record_count=len(records), duplicate_count=duplicates, rejected_count=rejected,
        compute=meter.compute(accepted_examples=len(records), discarded_examples=duplicates + rejected),
        created_at=utc_now(),
    ))


# ---------------------------------------------------------------------------
# L3 frozen datasets
# ---------------------------------------------------------------------------


def _split_for(group: str, seed: int, fractions: Sequence[float]) -> str:
    u = int(sha256_bytes(f"{seed}:{group}".encode())[7:15], 16) / 2**32
    if u < fractions[0]:
        return "train"
    return "val" if u < fractions[0] + fractions[1] else "test"


def _cp_bucket(record: dict) -> str:
    label = next((lab for lab in record["labels"] if lab["family"] == "eval_cp"), None)
    if label is None:
        return "unlabelled"
    cp = abs(float(label["value"]))
    return "0" if cp == 0 else "1-99" if cp < 100 else "100-299" if cp < 300 else "300-899" if cp < 900 else "900+"


def dataset_manifest_hash(dataset: Dataset) -> str:
    return hash_obj(dataset.model_dump(mode="json", exclude={"id", "created_at", "manifest_hash", "compute"}))


def freeze_dataset(store: Store, normalization_id: str, *, name: str, selection: Optional[Mapping[str, str]] = None,
                   split_seed: int = 0, fractions: Sequence[float] = (0.8, 0.1, 0.1),
                   required_labels: Sequence[str] = ("eval_cp",), parent_id: Optional[str] = None) -> Dataset:
    selection = {k: str(v) for k, v in (selection or {}).items()}
    bad = sorted(set(selection) - set(SELECTABLE_FIELDS))
    if bad:
        raise LabError(f"cannot select on {bad}; selectable fields: {SELECTABLE_FIELDS}")
    if len(fractions) != 3 or min(fractions) < 0 or abs(sum(fractions) - 1.0) > 1e-9:
        raise LabError("split fractions must be three non-negative numbers summing to 1")
    meter = _Meter()
    norm: Normalization = store.get(normalization_id)
    if sha256_file(store.abs(norm.path)) != norm.output_hash:
        raise TamperError(f"{norm.id}: canonical records no longer match the normalization output hash")
    kept, excluded, missing = [], 0, 0
    for record in read_jsonl(store.abs(norm.path)):
        if any(str(record.get(field)) != value for field, value in selection.items()):
            excluded += 1
            continue
        if not set(required_labels) <= {lab["family"] for lab in record["labels"]}:
            missing += 1
            continue
        kept.append(record)
    if not kept:
        raise LabError("selection retains no records; nothing to freeze")

    dataset_id = store.next_id("D")
    by_split: dict[str, list[dict]] = {s: [] for s in SPLIT_NAMES}
    for record in kept:
        by_split[_split_for(record["group"], split_seed, fractions)].append(record)
    manifests = []
    for split_name in SPLIT_NAMES:
        rows = by_split[split_name]
        rel = f"datasets/{dataset_id}/{split_name}.jsonl"
        file_hash = write_jsonl(store.abs(rel), rows)
        store.make_readonly(store.abs(rel))
        manifests.append(SplitManifest(
            name=split_name, count=len(rows), group_count=len({r["group"] for r in rows}), path=rel, file_hash=file_hash,
            record_ids_hash=hash_obj(sorted(r["record_id"] for r in rows)),
        ))
    dataset = Dataset(
        id=dataset_id, name=name, normalization_id=norm.id, normalization_recipe_hash=norm.recipe_hash,
        source_ids=norm.source_ids, canonical_schema_version=norm.canonical_schema_version,
        label_requirements=list(required_labels), selection=dict(selection),
        sampling_policy="natural concatenation of all selected records; no weighting or oversampling",
        dedup_policy=norm.dedup_policy,
        split_policy={"method": "group-hash", "group_key": "source game", "seed": split_seed,
                      "train": float(fractions[0]), "val": float(fractions[1]), "test": float(fractions[2])},
        splits=manifests,
        counts={"records": len(kept), "groups": len({r["group"] for r in kept}), "excluded_by_selection": excluded,
                "missing_required_labels": missing},
        coverage={
            "split": {s: len(by_split[s]) for s in SPLIT_NAMES},
            "phase": dict(Counter(r["phase"] for r in kept)),
            "stm": dict(Counter(r["stm"] for r in kept)),
            "abs_cp_bucket": dict(Counter(_cp_bucket(r) for r in kept)),
            "source": dict(Counter(r["source_id"] for r in kept)),
        },
        label_provenance=dict(Counter(lab["authority"] for r in kept for lab in r["labels"])),
        parent_id=parent_id, manifest_hash="",
        compute=meter.compute(accepted_examples=len(kept), discarded_examples=excluded + missing),
        created_at=utc_now(),
    )
    dataset.manifest_hash = dataset_manifest_hash(dataset)
    return store.create(dataset)


def load_split(store: Store, dataset: Dataset, split_name: str) -> list[dict]:
    manifest = next((s for s in dataset.splits if s.name == split_name), None)
    if manifest is None:
        raise LabError(f"{dataset.id} has no split {split_name!r}")
    return read_jsonl(store.abs(manifest.path))


def verify_dataset(store: Store, dataset: Dataset) -> list[IntegrityCheck]:
    checks = [make_check("dataset_manifest_hash", dataset_manifest_hash(dataset) == dataset.manifest_hash,
                         f"{dataset.id} manifest recomputes to its recorded hash")]
    problems: list[str] = []
    ids: dict[str, set[str]] = {}
    groups: dict[str, set[str]] = {}
    for manifest in dataset.splits:
        path = store.abs(manifest.path)
        if not path.exists():
            problems.append(f"{manifest.name}: file missing")
            continue
        if sha256_file(path) != manifest.file_hash:
            problems.append(f"{manifest.name}: file hash mismatch")
            continue
        rows = read_jsonl(path)
        row_ids = [r["record_id"] for r in rows]
        if len(rows) != manifest.count or hash_obj(sorted(row_ids)) != manifest.record_ids_hash:
            problems.append(f"{manifest.name}: record identities differ from manifest")
        ids[manifest.name] = set(row_ids)
        groups[manifest.name] = {r["group"] for r in rows}
    checks.append(make_check("dataset_files", not problems,
                             "; ".join(problems) or "every split file matches its manifest hash and record identities"))
    overlaps = [f"{a}/{b}: {len(ids[a] & ids[b])} positions, {len(groups[a] & groups[b])} games"
                for a, b in combinations(ids, 2) if ids[a] & ids[b] or groups[a] & groups[b]]
    checks.append(make_check("split_disjoint", not overlaps,
                             "; ".join(overlaps) or "no position or game appears in more than one split"))
    return checks
