"""Adapters that bring the existing engine/app system into canonical lab identities.

* ``import_legacy_catalog`` reads ``catalog/`` (generated by ``tools/intake/legacy_catalog.py``),
  re-verifies artifact bytes against the catalog hashes, and assigns lab identities once per
  content hash. Everything imported has lineage ``LEGACY``: permanently inspectable, never
  promotable, never inherited into the clean lineage. Search switches become clean-lineage
  backlog items whose legacy gate state sets re-test priority, not truth.
* ``import_funnel_run`` records an information-gain labeling funnel run (engine
  ``training/funnel``): tier costs, provenance classes, coverage, arms and the priority
  distribution, with the run's own hashes cross-checked.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import time
from collections import Counter
from pathlib import Path
from typing import Iterable, Mapping, Optional

from .hashing import sha256_file
from .schemas import (
    ArtifactLocation,
    Compute,
    EvidenceState,
    FileVerification,
    FunnelArm,
    FunnelFile,
    FunnelOracleArm,
    FunnelRun,
    FunnelTier,
    IntakeRecord,
    IntegrityCheck,
    LegacyChampion,
    LegacyEngine,
    LegacyEvaluation,
    LegacyEvidence,
    LegacyModel,
    LegacyRoot,
    LegacySource,
    LegacyFile,
    SearchProfile,
    SearchSwitch,
    SwitchGateRecord,
    make_check,
    utc_now,
)
from .store import LabError, Store

SUPPORTED_CATALOG_TOOL = "legacy-catalog-v1"
SUPPORTED_FUNNEL_SCHEMA = 1
CATALOG_FILES = ("manifest.json", "models.json", "sources.json", "evaluations.json", "evidence.json",
                 "engines.json", "switches.json")
FUNNEL_COPIED_FILES = ("manifest.json", "report.json", "funnel-config.json", "coverage.json", "report.md")
FUNNEL_STREAM_FILES = ("positions.jsonl", "tier0.jsonl", "tier1.jsonl", "triage.jsonl", "tier3.jsonl", "tier4.jsonl",
                       "triage-misses.jsonl")
PRIORITY_BINS = 20

BACKLOG = {
    EvidenceState.SUPPORTED: (1, "legacy gate promoted it; re-test first against the clean evaluator"),
    EvidenceState.INCONCLUSIVE: (2, "legacy gate held for more data; re-test once a clean baseline exists"),
    EvidenceState.PROPOSED: (3, "no legacy gate record; untested"),
    EvidenceState.REJECTED: (4, "legacy gate rejected it; re-test last, since it may interact differently with a new evaluator"),
}

SCALAR = (bool, int, float, str)


def _hex_sha256(path: Path) -> str:
    return sha256_file(path).removeprefix("sha256:")


def _load(path: Path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _git(root: Optional[Path], *args: str) -> Optional[str]:
    if root is None:
        return None
    try:
        out = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() if out.returncode == 0 else None


def _verify(path: Optional[Path], sha256: str, *, size: Optional[int] = None, hash_bytes: bool = True) -> FileVerification:
    if path is None:
        return "unverifiable"
    if not path.is_file():
        return "missing"
    if not hash_bytes:
        return "size-match" if size is None or path.stat().st_size == size else "size-mismatch"
    return "sha256-match" if _hex_sha256(path) == sha256 else "sha256-mismatch"


def _any_copy(results: Iterable[FileVerification]) -> FileVerification:
    """Identical bytes at several locations: one good copy verifies, any differing copy is a mismatch."""
    results = list(results)
    for bad in ("sha256-mismatch", "size-mismatch"):
        if bad in results:
            return bad
    for good in ("sha256-match", "size-match"):
        if good in results:
            return good
    return "missing" if "missing" in results else "unverifiable"


def _all_files(results: Iterable[FileVerification]) -> FileVerification:
    """A multi-file source verifies only when every file does."""
    results = list(results)
    for state in ("sha256-mismatch", "size-mismatch", "missing", "unverifiable"):
        if state in results:
            return state
    return "sha256-match" if "sha256-match" in results else "size-match"


def _summarize(name: str, results: Mapping[str, FileVerification]) -> IntegrityCheck:
    counts = Counter(results.values())
    bad = [k for k, v in results.items() if v.endswith("mismatch")]
    absent = [k for k, v in results.items() if v in ("missing", "unverifiable")]
    detail = ", ".join(f"{n} {state}" for state, n in sorted(counts.items()))
    if bad:
        detail += f"; bytes differ from the catalog: {', '.join(bad[:8])}"
    if absent:
        detail += f"; not available here: {', '.join(absent[:8])}{' …' if len(absent) > 8 else ''}"
    return IntegrityCheck(name=name, status="fail" if bad else "warn" if absent else "pass", detail=detail)


def _existing_legacy(store: Store) -> dict[tuple[str, str], str]:
    index: dict[tuple[str, str], str] = {}
    for m in store.list("M", verify=False, kind=LegacyModel):
        index[("M", m.sha256)] = m.id
    for s in store.list("S", verify=False, kind=LegacySource):
        index[("S", s.content_sha256)] = s.id
    for e in store.list("E", verify=False, kind=LegacyEvaluation):
        index[("E", e.sha256)] = e.id
    for r in store.list("R", verify=False, kind=LegacyEvidence):
        index[("R", r.sha256)] = r.id
    return index


# ---------------------------------------------------------------------------
# Legacy catalog
# ---------------------------------------------------------------------------


def import_legacy_catalog(store: Store, catalog_dir: str | Path, *, roots: Optional[Mapping[str, Optional[str]]] = None,
                          hash_sources: bool = False) -> IntakeRecord:
    catalog = Path(catalog_dir)
    missing = [name for name in CATALOG_FILES if not (catalog / name).is_file()]
    if missing:
        raise LabError(f"{catalog} is not a legacy catalog; missing {', '.join(missing)}")
    manifest = _load(catalog / "manifest.json")
    if manifest.get("tool") != SUPPORTED_CATALOG_TOOL:
        raise LabError(f"unsupported catalog tool {manifest.get('tool')!r}; expected {SUPPORTED_CATALOG_TOOL}")
    cpu0, wall0 = time.process_time(), time.perf_counter()
    overrides = {k: v for k, v in (roots or {}).items() if v}

    root_paths: dict[str, Path] = {}
    legacy_roots: list[LegacyRoot] = []
    checks: list[IntegrityCheck] = [make_check("catalog_tool", True, f"{SUPPORTED_CATALOG_TOOL}, generated {manifest.get('generatedAt')}")]
    for name, info in manifest.get("roots", {}).items():
        raw = overrides.get(name) or info.get("path")
        path = Path(raw) if raw and Path(raw).is_dir() else None
        if path:
            root_paths[name] = path
        git = info.get("git") or {}
        root = LegacyRoot(name=name, path=str(path) if path else raw, catalog_commit=git.get("commit"),
                          current_commit=_git(path, "rev-parse", "HEAD"), dirty=git.get("dirty"), remote=git.get("remote"))
        legacy_roots.append(root)
        if path is None:
            checks.append(make_check(f"root_{name}", False, f"{name} root {raw!r} is not available on this machine", warn=True))
        elif root.catalog_commit and root.current_commit and root.catalog_commit != root.current_commit:
            checks.append(make_check(f"root_{name}", False,
                                     f"catalog pinned {root.catalog_commit[:10]}; checkout is now {root.current_commit[:10]}; "
                                     "artifact bytes are re-verified by hash", warn=True))
        else:
            checks.append(make_check(f"root_{name}", True, f"{path}" + (f" at {root.current_commit[:10]}" if root.current_commit else "")))

    def resolve(location: Mapping) -> Optional[Path]:
        base = root_paths.get(location["root"])
        return base / location["path"] if base else None

    models = _load(catalog / "models.json")
    sources = _load(catalog / "sources.json")
    evaluations = _load(catalog / "evaluations.json")
    evidence = _load(catalog / "evidence.json")
    engines_doc = _load(catalog / "engines.json")
    switches_doc = _load(catalog / "switches.json")
    counts = manifest.get("counts", {})
    count_problems = [f"{name}: manifest {counts.get(name)} vs {len(rows)} entries"
                      for name, rows in (("models.json", models), ("sources.json", sources),
                                         ("evaluations.json", evaluations), ("evidence.json", evidence))
                      if counts.get(name) is not None and counts[name] != len(rows)]
    checks.append(make_check("catalog_counts", not count_problems, "; ".join(count_problems) or "entry counts match the catalog manifest"))

    intake_id = store.next_id("I")
    now = utc_now()
    existing = _existing_legacy(store)
    assigned: dict[str, list[str]] = {prefix: [] for prefix in "MSER"}
    reused: Counter = Counter()

    # -- models ----------------------------------------------------------------
    model_ids_by_sha: dict[str, str] = {}
    model_ids_by_name: dict[str, str] = {}
    results: dict[str, FileVerification] = {}
    for m in models:
        obj_id = existing.get(("M", m["sha256"]))
        if obj_id:
            reused["M"] += 1
        else:
            verification = _any_copy(_verify(resolve(loc), m["sha256"]) for loc in m["locations"])
            results[m["name"]] = verification
            obj = store.create(LegacyModel(
                id=store.next_id("M"), origin="legacy_catalog", intake_id=intake_id, name=m["name"], sha256=m["sha256"],
                bytes=m["bytes"], model_kind=m["modelKind"], serialized_param_count=m.get("serializedParameterCount"),
                metadata={k: v for k, v in (m.get("metadata") or {}).items() if v is None or isinstance(v, SCALAR)},
                role=m["role"], role_evidence=m.get("roleEvidence"), provenance_complete=bool(m.get("provenanceComplete")),
                locations=[ArtifactLocation(**loc) for loc in m["locations"]], verification=verification, created_at=now,
            ))
            obj_id = obj.id
            assigned["M"].append(obj_id)
        model_ids_by_sha[m["sha256"]] = obj_id
        for loc in m["locations"]:
            model_ids_by_name.setdefault(Path(loc["path"]).name, obj_id)
    if results:
        checks.append(_summarize("legacy_model_bytes", results))

    # -- sources ---------------------------------------------------------------
    results = {}
    for s in sources:
        if ("S", s["contentSha256"]) in existing:
            reused["S"] += 1
            continue
        manifest_files = s.get("fileManifest", [])
        file_results = [_verify(resolve(f), f["sha256"], size=f["bytes"], hash_bytes=hash_sources) for f in manifest_files]
        verification = _all_files(file_results) if file_results else "unverifiable"
        detail = ", ".join(f"{n} {state}" for state, n in sorted(Counter(file_results).items())) + f" over {len(file_results)} file(s)"
        content = hashlib.sha256("".join(f["sha256"] for f in manifest_files).encode()).hexdigest()
        if manifest_files and content != s["contentSha256"]:
            verification, detail = "sha256-mismatch", detail + "; catalog content hash does not match its file manifest"
        if not hash_sources and verification == "size-match":
            detail += " (sizes only; pass --hash-sources to hash every byte)"
        results[s["name"]] = verification
        obj = store.create(LegacySource(
            id=store.next_id("S"), origin="legacy_catalog", intake_id=intake_id, name=s["name"],
            content_sha256=s["contentSha256"], files=s["files"], rows=s["rows"], bytes=s["bytes"],
            sample_fields=list(s.get("sampleFields", [])), field_authority=dict(s.get("fieldAuthority", {})),
            note=s.get("note"), bytes_availability=s.get("bytesAvailability", "unknown"),
            file_manifest=[LegacyFile(root=f["root"], path=f["path"], sha256=f["sha256"], bytes=f["bytes"], rows=f["rows"])
                           for f in manifest_files],
            verification=verification, verification_detail=detail, created_at=now,
        ))
        assigned["S"].append(obj.id)
    if results:
        checks.append(_summarize("legacy_source_files", results))

    # -- evaluation instruments ------------------------------------------------
    results = {}
    for e in evaluations:
        if ("E", e["sha256"]) in existing:
            reused["E"] += 1
            continue
        verification = _verify(resolve(e["location"]), e["sha256"])
        results[e["location"]["path"]] = verification
        obj = store.create(LegacyEvaluation(
            id=store.next_id("E"), origin="legacy_catalog", intake_id=intake_id, name=e["name"], kind=e["kind"],
            sha256=e["sha256"], bytes=e["bytes"], location=ArtifactLocation(**e["location"]), verification=verification,
            created_at=now,
        ))
        assigned["E"].append(obj.id)
    if results:
        checks.append(_summarize("legacy_evaluation_bytes", results))

    # -- gate and measurement evidence -----------------------------------------
    registry = switches_doc["registry"]
    switches_by_record: dict[str, set[str]] = {}
    for sw in registry["switches"]:
        ev = sw.get("evidence") or {}
        for record in ([ev["current"]] if ev.get("current") else []) + list(ev.get("history", [])):
            switches_by_record.setdefault(record["record"], set()).add(sw["id"])
    evidence_ids_by_path: dict[str, str] = {}
    results = {}
    for e in evidence:
        path = e["location"]["path"]
        obj_id = existing.get(("R", e["sha256"]))
        if obj_id:
            reused["R"] += 1
        else:
            recorded = e.get("labState", "")
            state = EvidenceState(recorded) if recorded in EvidenceState.__members__ else None
            verification = _verify(resolve(e["location"]), e["sha256"])
            results[path] = verification
            obj = store.create(LegacyEvidence(
                id=store.next_id("R"), origin="legacy_catalog", intake_id=intake_id, type=e["type"],
                location=ArtifactLocation(**e["location"]), sha256=e["sha256"], date=e.get("date"),
                baseline_id=e.get("baselineId"), candidate_id=e.get("candidateId"), games=e.get("games"),
                wdl=e.get("wdl"), llr=e.get("llr"), boundary=e.get("boundary"), decision=e.get("decision"),
                recorded_state=recorded, evidence_state=state, is_measurement=state is None, note=e.get("note"),
                switch_ids=sorted(switches_by_record.get(path, set())), verification=verification, created_at=now,
            ))
            obj_id = obj.id
            assigned["R"].append(obj_id)
        evidence_ids_by_path[path] = obj_id
    if results:
        checks.append(_summarize("legacy_evidence_bytes", results))

    # -- search switches as clean-lineage backlog --------------------------------
    def gate(record: Mapping) -> SwitchGateRecord:
        return SwitchGateRecord(record=record["record"], evidence_id=evidence_ids_by_path.get(record["record"]),
                                date=record.get("date"), games=record.get("games"), llr=record.get("llr"),
                                boundary=record.get("boundary"), decision=record.get("decision"),
                                legacy_state=record.get("labState", ""))

    switches = []
    for sw in registry["switches"]:
        legacy_state = EvidenceState(sw.get("labState", "PROPOSED"))
        tier, reason = BACKLOG.get(legacy_state, (3, "legacy state has no backlog rule"))
        ev = sw.get("evidence") or {}
        default = sw.get("default")
        switches.append(SearchSwitch(
            id=sw["id"], kind=sw["kind"], field=sw["field"], on_flag=sw.get("on"), off_flag=sw.get("off"),
            value_flag=sw.get("flag"), default=default if isinstance(default, SCALAR) else None, doc=sw.get("doc"),
            legacy_state=legacy_state, current=gate(ev["current"]) if ev.get("current") else None,
            history=[gate(r) for r in ev.get("history", [])], clean_state=EvidenceState.PROPOSED,
            backlog_tier=tier, backlog_reason=reason,
        ))
    switches.sort(key=lambda s: (s.backlog_tier, s.id))
    engine_root = root_paths.get("engine")
    live_registry = engine_root / "benchmarks" / "search-switches.json" if engine_root else None
    if live_registry and live_registry.is_file():
        live_sha = _hex_sha256(live_registry)
        checks.append(make_check("switch_registry_current", live_sha == switches_doc.get("sha256"),
                                 f"catalog snapshot {str(switches_doc.get('sha256'))[:12]}; engine checkout {live_sha[:12]}",
                                 warn=True))

    # -- engine identities, profiles and the legacy champion ---------------------
    engine_registry = engines_doc["registry"]
    engines = [LegacyEngine(
        id=e["id"], display_name=e.get("displayName"), generation=e.get("generation"), status=e.get("status"),
        architecture=e.get("architecture"), search_profile=e.get("searchProfile"), main_net=e.get("mainNet"),
        main_net_model_id=model_ids_by_name.get(Path(str(e.get("mainNet") or "")).name),
    ) for e in engine_registry.get("engines", [])]
    profiles = [SearchProfile(
        name=name, status=p.get("status"), args=list(p.get("args", [])),
        effective_options={k: v for k, v in (p.get("effectiveOptions") or {}).items() if isinstance(v, SCALAR)},
        notes=p.get("notes"),
    ) for name, p in engine_registry.get("searchProfiles", {}).items()]

    champion = None
    n0_path = engine_root / "benchmarks" / "N0-identity.json" if engine_root else None
    if n0_path and n0_path.is_file():
        n0 = _load(n0_path)
        artifacts = n0.get("artifacts", {})
        champion = LegacyChampion(
            engine_id=n0["engineId"], role=n0.get("role", "N0"), search_profile=n0.get("searchProfile"),
            live_bot_flags=list(n0.get("liveBotFlags", [])),
            main_net_model_id=model_ids_by_sha.get((artifacts.get("mainNet") or {}).get("sha256")),
            helper_net_model_id=model_ids_by_sha.get((artifacts.get("helperNet") or {}).get("sha256")),
            source_path="engine:benchmarks/N0-identity.json", sha256=_hex_sha256(n0_path),
            open_followups=list(n0.get("openFollowups", [])),
        )
        checks.append(make_check("legacy_champion", True, f"{champion.engine_id} from engine benchmarks/N0-identity.json"))
    else:
        checks.append(make_check("legacy_champion", False, "engine benchmarks/N0-identity.json not found", warn=True))

    ambiguous = sum(1 for s in sources if any(v.startswith(("ambiguous", "unknown")) for v in s.get("fieldAuthority", {}).values()))
    findings = [
        f"{sum(not m.get('provenanceComplete') for m in models)} of {len(models)} legacy models lack trainingCommit + "
        "datasetManifestHash; they are imported as non-promotable LEGACY artifacts.",
        f"{ambiguous} of {len(sources)} legacy sources have fields of ambiguous or unaudited authority; the first "
        "N#### over them must assign explicit provenance classes.",
        "Legacy evidence states: " + ", ".join(f"{k} {v}" for k, v in sorted(Counter(e.get("labState") for e in evidence).items())) + ".",
        f"{len(switches)} search switches enter the clean lineage as PROPOSED backlog items; legacy gate states set "
        "re-test priority only.",
        "No legacy model, search profile or corpus weighting is inherited by the clean lineage; a warm start from a "
        "legacy net must be an explicit ablation.",
    ]

    record = IntakeRecord(
        id=intake_id, tool=SUPPORTED_CATALOG_TOOL, catalog_dir=str(catalog.resolve()),
        catalog_generated_at=str(manifest.get("generatedAt")),
        catalog_file_hashes={name: sha256_file(catalog / name) for name in CATALOG_FILES},
        roots=legacy_roots, assigned=assigned, reused=dict(reused), engines=engines, search_profiles=profiles,
        switches=switches, engine_args=[{k: str(v) for k, v in a.items()} for a in registry.get("engineArgs", [])],
        unmatched_gate_records=len(registry.get("unmatchedGateRecords", [])), champion=champion,
        flagship_model_ids=[model_ids_by_sha[m["sha256"]] for m in models if str(m.get("role", "")).startswith("flagship-")],
        findings=findings, integrity=checks,
        compute=Compute(cpu_seconds=round(time.process_time() - cpu0, 4), wall_seconds=round(time.perf_counter() - wall0, 4)),
        created_at=now,
    )
    return store.create(record)


# ---------------------------------------------------------------------------
# Labeling funnel runs
# ---------------------------------------------------------------------------


def _hash_and_count(path: Path) -> tuple[str, int, int]:
    digest, size, rows, last = hashlib.sha256(), 0, 0, b"\n"
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
            size += len(chunk)
            rows += chunk.count(b"\n")
            last = chunk[-1:]
    if size and last != b"\n":
        rows += 1
    return digest.hexdigest(), size, rows


def _floats(mapping: Optional[Mapping]) -> dict[str, float]:
    return {k: float(v) for k, v in (mapping or {}).items() if isinstance(v, (int, float)) and not isinstance(v, bool)}


def import_funnel_run(store: Store, run_dir: str | Path, *, name: Optional[str] = None,
                      research_state: Optional[str] = None, state_source: Optional[str] = None) -> FunnelRun:
    directory = Path(run_dir)
    for required in ("manifest.json", "report.json"):
        if not (directory / required).is_file():
            raise LabError(f"{directory} is not a funnel run directory; missing {required}")
    manifest = _load(directory / "manifest.json")
    report = _load(directory / "report.json")
    if manifest.get("funnelSchemaVersion") != SUPPORTED_FUNNEL_SCHEMA or report.get("funnelSchemaVersion") != SUPPORTED_FUNNEL_SCHEMA:
        raise LabError(f"unsupported funnel schema; expected funnelSchemaVersion {SUPPORTED_FUNNEL_SCHEMA}")
    state = None
    if research_state:
        if not state_source:
            raise LabError("a research state must cite the document that records it (state_source)")
        try:
            state = EvidenceState(research_state.upper())
        except ValueError:
            raise LabError(f"unknown evidence state {research_state!r}") from None
    manifest_sha = _hex_sha256(directory / "manifest.json")
    for existing in store.list("R", verify=False, kind=FunnelRun):
        if any(f.name == "manifest.json" and f.sha256 == manifest_sha for f in existing.files):
            raise LabError(f"this funnel run is already imported as {existing.id}")

    run_id = store.next_id("R")
    files: list[FunnelFile] = []
    rows: dict[str, int] = {}
    for file_name in FUNNEL_COPIED_FILES:
        path = directory / file_name
        if path.is_file():
            payload = path.read_bytes()
            rel, _ = store.write_artifact(run_id, file_name, payload)
            files.append(FunnelFile(name=file_name, sha256=hashlib.sha256(payload).hexdigest(), bytes=len(payload),
                                    rows=None, copied_to=rel))
    for file_name in FUNNEL_STREAM_FILES:
        path = directory / file_name
        if path.is_file():
            digest, size, count = _hash_and_count(path)
            rows[file_name] = count
            files.append(FunnelFile(name=file_name, sha256=digest, bytes=size, rows=count, copied_to=None))

    engine = manifest.get("engine", {})
    tiers_report = report.get("tiers", {})
    stages = manifest.get("stages", {})
    config_path = directory / "funnel-config.json"
    checks = [
        make_check("config_hash", config_path.is_file() and _hex_sha256(config_path) == manifest.get("configSha256"),
                   "funnel-config.json hashes to the manifest's configSha256"),
        make_check("report_matches_manifest",
                   report.get("manifest", {}).get("configSha256") == manifest.get("configSha256")
                   and report.get("engineBinarySha256") == engine.get("binarySha256"),
                   "report was produced from this manifest's config and engine binary"),
    ]
    expected_rows = {
        "positions.jsonl": stages.get("sample", {}).get("sampled"),
        "tier0.jsonl": tiers_report.get("tier0", {}).get("positions"),
        "tier1.jsonl": tiers_report.get("tier1", {}).get("positions"),
        "triage.jsonl": stages.get("triage", {}).get("ranked"),
        "tier3.jsonl": tiers_report.get("tier3", {}).get("positions"),
        "tier4.jsonl": tiers_report.get("tier4", {}).get("positions"),
    }
    row_problems = [f"{f}: {rows.get(f)} rows vs {n} reported" for f, n in expected_rows.items() if n is not None and rows.get(f) != n]
    checks.append(make_check("tier_row_counts", not row_problems,
                             "; ".join(row_problems) or "every tier file holds the row count its report states"))
    legacy_models = {m.sha256: m.id for m in store.list("M", verify=False, kind=LegacyModel)}
    engine_artifacts = dict(engine.get("artifactSha256", {}))
    linked = {path: legacy_models[sha] for path, sha in engine_artifacts.items() if sha in legacy_models}
    checks.append(make_check("engine_artifacts_catalogued", len(linked) == len(engine_artifacts),
                             f"{len(linked)}/{len(engine_artifacts)} engine artifacts match legacy catalog models"
                             + ("" if legacy_models else " (legacy catalog not imported yet)"), warn=True))

    histogram = [0] * PRIORITY_BINS
    reasons: Counter = Counter()
    selection: Counter = Counter()
    triage_path = directory / "triage.jsonl"
    if triage_path.is_file():
        with open(triage_path, "rb") as fh:
            for line in fh:
                if not line.strip():
                    continue
                row = json.loads(line)
                priority = float(row.get("priority", 0.0))
                histogram[min(PRIORITY_BINS - 1, max(0, int(priority * PRIORITY_BINS)))] += 1
                for reason in row.get("reasons", []):
                    reasons[reason if isinstance(reason, str) else str(reason.get("component", reason))] += 1
                chosen = row.get("selection", {})
                for arm in ("deep", "uniform", "audit", "holdout"):
                    selection[arm] += bool(chosen.get(arm))
                selection["stockfish"] += bool(chosen.get("stockfish"))
                selection["train_eligible"] += bool(row.get("trainEligible"))

    provenance_classes = {k: str(v) for k, v in manifest.get("provenanceClasses", {}).items()}
    wall = report.get("wallClockSec", {})
    tiers = [FunnelTier(
        name=tier, positions=int(t.get("positions", 0)), engine_seconds=float(t.get("engineSec", 0.0)),
        ms_per_position=float(t.get("msPerPosition", 0.0)), nodes=int(t.get("nodes", 0)),
        wall_seconds=wall.get(tier), provenance_classes=[k for k, v in provenance_classes.items() if tier in v],
    ) for tier, t in tiers_report.items() if isinstance(t, dict)]
    coverage = report.get("coverage", {})
    provenance_records = {k: int(v) for k, v in coverage.get("provenanceRecords", {}).items()}
    experiment = report.get("experiment", {})
    total_engine_seconds = float(tiers_report.get("totalEngineSec", sum(t.engine_seconds for t in tiers)))
    taxonomy = manifest.get("taxonomy", {})
    tooling = manifest.get("toolingGit", {})

    run = FunnelRun(
        id=run_id, origin="funnel",
        lineage_note="Labels were produced by the legacy engine identity (flagship nets). They are usable as data and "
                     "evidence, not as clean-lineage model provenance.",
        name=name or directory.name, run_dir=str(directory.resolve()),
        funnel_schema_version=manifest["funnelSchemaVersion"], funnel_config_version=int(manifest.get("funnelConfigVersion", 0)),
        prioritizer_version=str(manifest.get("prioritizerVersion")), config_sha256=str(manifest.get("configSha256")),
        source_created_at=str(manifest.get("createdAt")), tooling_commit=tooling.get("commit"), tooling_dirty=tooling.get("dirty"),
        engine_binary_sha256=engine.get("binarySha256"), engine_artifacts=engine_artifacts, engine_artifact_model_ids=linked,
        engine_options={k: v for k, v in engine.get("identity", {}).get("options", {}).items() if isinstance(v, SCALAR)},
        stockfish_sha256=manifest.get("stockfish", {}).get("binarySha256"), taxonomy_version=taxonomy.get("schemaVersion"),
        taxonomy_sha256=taxonomy.get("sha256"), facts_registry_version=report.get("factsRegistryVersion"),
        provenance_classes=provenance_classes,
        sample={k: v for k, v in stages.get("sample", {}).items() if isinstance(v, SCALAR)},
        tiers=tiers, total_engine_seconds=total_engine_seconds, provenance_records=provenance_records,
        coverage={key: {k: int(v) for k, v in coverage[key].items()}
                  for key in ("slugs", "families", "phases", "materialBucketsTop") if isinstance(coverage.get(key), dict)},
        underrepresented=[str(s) for s in coverage.get("underrepresented", [])],
        selection=dict(selection), priority_histogram=histogram, priority_reasons=dict(reasons.most_common(20)),
        arms=[FunnelArm(
            name=arm, n=int(a.get("n", 0)), deep_nodes=int(a.get("deepNodes", 0)),
            deep_engine_seconds=float(a.get("deepEngineSec", 0.0)), informative=int(a.get("informative", 0)),
            informative_rate=float(a.get("informativeRate", 0.0)), move_change_rate=float(a.get("moveChangeRate", 0.0)),
            abs_shallow_deep_delta_cp=_floats(a.get("absShallowDeepDeltaCp")),
        ) for arm, a in report.get("arms", {}).items()],
        oracle_arms=[FunnelOracleArm(
            name=arm, n=int(a.get("n", 0)), disagreement_rate=float(a.get("disagreementRate", 0.0)),
            move_agreement_rate=float(a.get("moveAgreementRate", 0.0)), abs_cp=_floats(a.get("cvsDeepVsSfAbsCp")),
        ) for arm, a in report.get("oracleArms", {}).items()],
        audit_miss=_floats(report.get("auditMissEstimate")),
        experiment_question=str(experiment.get("question", "")),
        informative_yield_ratio=experiment.get("informativeYieldRatio"),
        experiment_caveat=str(experiment.get("caveat", "")),
        research_state=state, research_state_source=state_source if state else None,
        compute=Compute(
            cpu_seconds=total_engine_seconds, wall_seconds=round(sum(v for v in wall.values() if isinstance(v, (int, float))), 3),
            search_nodes=sum(t.nodes for t in tiers), labels_generated=provenance_records,
            oracle_labels=int(tiers_report.get("tier4", {}).get("positions", 0)),
            accepted_examples=int(stages.get("sample", {}).get("sampled", 0) or 0),
        ),
        compute_note="cpu_seconds are the funnel's single-thread engine-seconds; wall_seconds are per-tier wall clock with parallel workers.",
        files=files, integrity=checks, created_at=utc_now(),
    )
    return store.create(run)
