"""Verify the S0002 pool can be regenerated byte-identically with truthful provenance."""
import json, sys
from pathlib import Path
sys.path.insert(0, r"F:\Github\chess-vision-studio-lab")
from cvslab.funnel.pool import (DEFAULT_ENGINE_ARGS, PoolConfig, AnalyzeTeacher, SelfPlayGenerator,
                                engine_identity, write_pool)
from cvslab.funnel.providers import AnalyzeTransport

ENGINE = r"F:\Github\chess-vision-studio-rust-engine"
OUT = Path(r"F:\Github\_parity_tmp\s6\pool-corrected")
config = PoolConfig(seed=20260915, games=70, max_plies=70, sample_every=2, min_ply=6,
                    diversification_plies=(8, 10, 12), diversification_candidates=3,
                    diversification_window_cp=25, play_node_budget=20000,
                    diversification_node_budget=2000)
identity = engine_identity(ENGINE, args=DEFAULT_ENGINE_ARGS)
transport = AnalyzeTransport(ENGINE, args=DEFAULT_ENGINE_ARGS, cwd=ENGINE)
try:
    generated = SelfPlayGenerator(config, AnalyzeTeacher(transport)).generate()
finally:
    transport.close()
manifest = write_pool(OUT, generated, {"config": config.canonical(), "engine": identity},
                      opening_lines=config.effective_openings())
sha = manifest["positionsFile"]["sha256"]
print(json.dumps({"positions_sha256": sha, "matches_s0002": sha == "sha256:732ff062da25152ec3ad3dd755a81b660c1227687204b300ca127b2b77374bc1",
                  "engine": {"commit": identity["commit"], "binarySha256": identity["binarySha256"],
                             "netHashes": identity["netHashes"], "missingFiles": identity["missingFiles"]},
                  "configSha256": manifest["configSha256"]}, indent=1))
